# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site.

# ----------------------- #
#   Site Functionality    #
# ----------------------- #

# URL and Base URL - VERY IMPORTANT
# url: The main domain of your site. e.g. https://mmistakes.github.io
# baseurl: The subpath of your site. e.g. /minimal-mistakes
#
# If you are hosting on GitHub Pages, your settings will be:
# url: "https://your-username.github.io"
# baseurl: "/your-repository-name"
#
url: "https://[your-username].github.io" # <-- EDIT THIS
baseurl: "/The-Architects-Atlas" # <-- VERIFY THIS MATCHES YOUR REPO NAME EXACTLY

# ----------------------- #
#   Site Information      #
# ----------------------- #

# Site title, description, and author name
title: "The Architect's Atlas"
description: "A public library of practical guides, technical analysis, and reflective essays on technology and innovation."
author:
  name: "[Your Name]" # <-- EDIT THIS
  avatar: # "/assets/images/bio-photo.jpg" # You can add a photo later
  bio: "A lifelong problem-solver documenting a journey of turning limitations into advantages."
  location: "[Your City, Country]" # <-- EDIT THIS
  links:
    - label: "View My Work on GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/[your-username]" # <-- EDIT THIS

# ----------------------- #
#   Theme and Plugins     #
# ----------------------- #

# The theme and its plugins
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# ----------------------- #
#   Site Navigation       #
# ----------------------- #

# The links that appear at the top of your site
main:
  - title: "Practical Guides"
    url: /guides/
  - title: "Explained Articles"
    url: /articles/
  - title: "Creator's Journal"
    url: /journal/
  - title: "About This Project"
    url: /about/

# Defaults for posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
