# Site settings
# These are used to personalize your new site.
title: The Architect's Atlas
name: "[Your Name]"
description: "A public library of practical guides, technical analysis, and reflective essays on technology and innovation."
url: "https://your-username.github.io" # IMPORTANT: Replace with your GitHub Pages URL
baseurl: "/The-Architects-Atlas" # The name of your repository

# Remote theme
# This tells GitHub Pages to use the Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Using a specific version for stability

# Minimal Mistakes Plugins
plugins:
  - jekyll-include-cache

# Author Settings (for the sidebar)
author:
  name: "[Your Name]"
  avatar: "/assets/images/bio-photo.jpg" # We will add this image later
  bio: "A lifelong tinkerer and problem-solver, documenting my journey of turning limitations into advantages."
  location: "[Your City, Country]"
  links:
    - label: "View My Work on GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/your-username" # IMPORTANT: Replace with your username

# Site Navigation (the links at the top)
main:
  - title: "Guides"
    url: /guides/
  - title: "Articles"
    url: /articles/
  - title: "Journal"
    url: /journal/
  - title: "About"
    url: /about/
