# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
*   # yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.data.variable }}.
title: The Architect's Atlas
name: "[Your Name]"
description: "A public library of practical guides, technical analysis, and reflective essays on technology and innovation."
url: "https://your-username.github.io" # IMPORTANT: Replace with your GitHub Pages URL
baseurl: "/The-Architects-Atlas" # The name of your repository

# Remote theme
# This is the line that tells GitHub Pages to use the Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes Plugins
plugins:
  - jekyll-include-cache
